// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYFLAprZ0QjZ8R9mIBiTtpaAJi7WPOPns',
    appId: '1:100382217810:web:9dfead15d26d303e52318b',
    messagingSenderId: '100382217810',
    projectId: 'spruce-clean',
    authDomain: 'spruce-clean.firebaseapp.com',
    storageBucket: 'spruce-clean.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTPLXIKCSCli5RD9qFiFgGHl4BRN8bWJM',
    appId: '1:100382217810:android:b4b57fe83351e2a652318b',
    messagingSenderId: '100382217810',
    projectId: 'spruce-clean',
    storageBucket: 'spruce-clean.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb0nNmnbFb4HnK7ND21RH0iwJL5bdRdVw',
    appId: '1:100382217810:ios:481205baa71d977952318b',
    messagingSenderId: '100382217810',
    projectId: 'spruce-clean',
    storageBucket: 'spruce-clean.appspot.com',
    iosClientId: '100382217810-iqul4b3fe4kb729fr8duf8jvqifa9qkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb0nNmnbFb4HnK7ND21RH0iwJL5bdRdVw',
    appId: '1:100382217810:ios:481205baa71d977952318b',
    messagingSenderId: '100382217810',
    projectId: 'spruce-clean',
    storageBucket: 'spruce-clean.appspot.com',
    iosClientId: '100382217810-iqul4b3fe4kb729fr8duf8jvqifa9qkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanAdmin',
  );
}
